import dash_core_components as dcc
import dash_html_components as html
import dash_bootstrap_components as dbc
import plotly.graph_objects as go


def generate_layout():
    """Generate dashboard layout"""
    return html.Div(children=[dcc.Tabs(
        [dcc.Tab(label="Train AI",
                 children=[html.H1(children="AI learns snake"),
                           html.Div([html.Hr(),
                                     dbc.Row([dbc.Col([html.H3(children='Settings',
                                                               style={'textAlign': 'left'}),
                                                       html.P(children='Number of generations:',
                                                              style={'textAlign': 'left',
                                                                     'margin': '5px'}),
                                                       dcc.Input(id='number_of_generations',
                                                                 value=400,
                                                                 type='number',
                                                                 style={"margin": "5px",
                                                                        "width": "100%"}),
                                                       html.P(children='Population_size:',
                                                              style={'textAlign': 'left',
                                                                     'margin': '5px'}),
                                                       dcc.Input(id='population_size',
                                                                 value=1000,
                                                                 type='number',
                                                                 style={"margin": "5px",
                                                                        "width": "100%"}),
                                                       html.P(children='Survival percentage (%):',
                                                              style={'textAlign': 'left',
                                                                     'margin': '5px'}),
                                                       dcc.Input(id='survival_perc',
                                                                 value=1,
                                                                 type='number',
                                                                 min=0,
                                                                 max=100,
                                                                 style={"margin": "5px",
                                                                        "width": "100%"}),
                                                       html.P(children='Parent percentage (%):',
                                                              style={'textAlign': 'left',
                                                                     'margin': '5px'}),
                                                       dcc.Input(id='parent_perc',
                                                                 value=20,
                                                                 type='number',
                                                                 min=0,
                                                                 max=100,
                                                                 style={"margin": "5px",
                                                                        "width": "100%"}),
                                                       html.P(children='Mutation percentage (%):',
                                                              style={'textAlign': 'left',
                                                                     'margin': '5px'}),
                                                       dcc.Input(id='mutation_perc',
                                                                 value=5,
                                                                 type='number',
                                                                 min=0,
                                                                 max=100,
                                                                 style={"margin": "5px",
                                                                        "width": "100%"}),
                                                       html.Div([dbc.Button('Train AI',
                                                                            id="train_ai_button",
                                                                            color="primary",
                                                                            style={"margin": "5px",
                                                                                   "width": "100%"}),
                                                                 html.Div(id='train_ai_button_triggered',
                                                                          children=False),
                                                                 html.Div(id='output_folder',
                                                                          children=None,
                                                                          hidden=True)])],
                                             width=2),
                                             dbc.Col([dcc.Dropdown(id='metric_drop_down',
                                                                   value="score",
                                                                   clearable=False,
                                                                   options=[{'label': 'Fitness',
                                                                             'value': 'fitness'},
                                                                            {'label': 'Score',
                                                                             'value': 'score'}])],
                                             width=1),
                                             dbc.Col([dcc.Graph(id='display'),
                                                      dcc.Interval(id='interval',
                                                                   interval=1 * 1000,
                                                                   n_intervals=0)])])])]),
         dcc.Tab(label='Snake AI',
                 children=[html.H1(children="AI plays snake"),
                           html.Div([html.Hr(),
                                     dbc.Row([dbc.Col([
                                              html.H3(children='Settings',
                                                      style={'textAlign': 'left'}),
                                              html.P(children='Select training moment:',
                                                     style={'textAlign': 'left',
                                                            'margin': '5px'}),
                                              dcc.Dropdown(id='session_selection',
                                                           options=[{'label': 'Test',
                                                                     'value': 'test_value'}]),
                                              html.P(children='Select generation',
                                                     style={'textAlign': 'left',
                                                            'margin': '5px'}),
                                              dcc.Dropdown(id='generation_selection',
                                                           options=[{'label': 'Test',
                                                                     'value': 'test_value'}]),
                                              dcc.Interval(id='session_interval',
                                                           interval=1 * 1000,
                                                           n_intervals=0),
                                              html.Div([dbc.Button('Play',
                                                                   id="play_ai_button",
                                                                   color="primary",
                                                                   style={"margin": "5px",
                                                                          "width": "100%"}),
                                                        dcc.Interval(id='snake_interval',
                                                                     interval=0.1 * 1000,
                                                                     n_intervals=0),
                                                        html.Div(id='snake_location',
                                                                 children=None,
                                                                 hidden=True)])],
                                              width=3),
                                              dbc.Col([dcc.Graph(id='play_snake',
                                                                 figure=go.Figure(),
                                                                 config={'displayModeBar': False})])])])])])])
